In [32]:
import pandas as pd
import numpy as np

In [33]:
ad_df = pd.read_csv('ad_placement/census-income.csv')

In [34]:
ad_df.head()

,AAGE,ACLSWKR,ADTIND,ADTOCC,AHGA,AHRSPAY,AHSCOL,AMARITL,AMJIND,AMJOCC,...,PEFNTVTY,PEMNTVTY,PENATVTY,PRCITSHP,SEOTR,VETQVA,VETYN,WKSWORK,YEAR,INCOME_IND
0,73,Not in universe,0,0,High school graduate,0,Not in universe,Widowed,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,-50000
1,58,Self-employed-not incorporated,4,34,Some college but no degree,0,Not in universe,Divorced,Construction,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
2,18,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,...,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,-50000
3,9,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
4,10,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000

In [35]:
ad_df.shape

(199523, 42)

In [36]:
ad_df.dtypes

AAGE            int64
ACLSWKR        object
ADTIND          int64
ADTOCC          int64
AHGA           object
AHRSPAY         int64
AHSCOL         object
AMARITL        object
AMJIND         object
AMJOCC         object
ARACE          object
AREORGN        object
ASEX           object
AUNMEM         object
AUNTYPE        object
AWKSTAT        object
CAPGAIN         int64
CAPLOSS         int64
DIVVAL          int64
FILESTAT       object
GRINREG        object
GRINST         object
HHDFMX         object
HHDREL         object
MARSUPWT      float64
MIGMTR1        object
MIGMTR3        object
MIGMTR4        object
MIGSAME        object
MIGSUN         object
NOEMP           int64
PARENT         object
PEFNTVTY       object
PEMNTVTY       object
PENATVTY       object
PRCITSHP       object
SEOTR           int64
VETQVA         object
VETYN           int64
WKSWORK         int64
YEAR            int64
INCOME_IND     object
dtype: object

In [37]:
ad_df = ad_df.replace(' ?', np.nan)

In [38]:
ad_df

,AAGE,ACLSWKR,ADTIND,ADTOCC,AHGA,AHRSPAY,AHSCOL,AMARITL,AMJIND,AMJOCC,...,PEFNTVTY,PEMNTVTY,PENATVTY,PRCITSHP,SEOTR,VETQVA,VETYN,WKSWORK,YEAR,INCOME_IND
0,73,Not in universe,0,0,High school graduate,0,Not in universe,Widowed,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,-50000
1,58,Self-employed-not incorporated,4,34,Some college but no degree,0,Not in universe,Divorced,Construction,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
2,18,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,...,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,-50000
3,9,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
4,10,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
5,48,Private,40,10,Some college but no degree,1200,Not in universe,Married-civilian spouse present,Entertainment,Professional specialty,...,Philippines,United-States,United-States,Native- Born in the United States,2,Not in universe,2,52,95,-50000
6,42,Private,34,3,Bachelors degree(BA AB BS),0,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
7,28,Private,4,40,High school graduate,0,Not in universe,Never married,Construction,Handlers equip cleaners etc,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,30,95,-50000
8,47,Local government,43,26,Some college but no degree,876,Not in universe,Married-civilian spouse present,Education,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,-50000
9,34,Private,4,37,Some college but no degree,0,Not in universe,Married-civilian spouse present,Construction,Machine operators assmblrs & inspctrs,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
10,8,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
11,32,Not in universe,0,0,High school graduate,0,Not in universe,Never married,Not in universe or children,Not in universe,...,NaN,NaN,NaN,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,-50000
12,51,Private,4,34,Some college but no degree,0,Not in universe,Married-civilian spouse present,Construction,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
13,46,Private,37,31,High school graduate,0,Not in universe,Divorced,Business and repair services,Other service,...,Columbia,Columbia,Columbia,Foreign born- Not a citizen of U S,0,Not in universe,2,52,94,-50000
14,26,Private,24,12,Bachelors degree(BA AB BS),0,Not in universe,Never married,Manufacturing-nondurable goods,Professional specialty,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,-50000
15,13,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
16,47,Private,39,36,Bachelors degree(BA AB BS),0,Not in universe,Never married,Personal services except private HH,Machine operators assmblrs & inspctrs,...,Germany,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,-50000
17,39,Not in universe,0,0,10th grade,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,Mexico,Mexico,Mexico,Foreign born- Not a citizen of U S,0,Not in universe,2,0,94,-50000
18,16,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,...,United-States,El-Salvador,United-States,Native- Born in the United States,0,Not in universe,2,0,95,-50000
19,35,Private,12,41,High school graduate,0,Not in universe,Married-civilian spouse present,Manufacturing-durable goods,Handlers equip cleaners etc,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,49,95,-50000
20,12,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
21,27,Self-employed-not incorporated,4,34,Some college but no degree,0,Not in universe,Married-civilian spouse present,Construction,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,1,Not in universe,2,52,94,-50000
22,56,Private,35,22,Some college but no degree,500,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,32,95,-50000
23,46,Private,45,12,Masters degree(MA MS MEng MEd MSW MBA),0,Not in universe,Married-civilian spouse present,Other professional services,Professional specialty,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
24,55,Not in universe,0,0,Some college but no degree,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,Japan,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,94,-50000
25,2,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
26,1,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,NaN,NaN,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
27,37,Private,3,34,Some college but no degree,0,Not in universe,Married-civilian spouse present,Mining,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,-50000
28,4,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,95,-50000
29,37,Private,4,2,Bachelors degree(BA AB BS),0,Not in universe,Never married,Construction,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199493,13,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
199494,5,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
199495,44,Self-employed-not incorporated,38,2,Some college but no degree,0,Not in universe,Married-civilian spouse present,Business and repair services,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,50,94,-50000
199496,1,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
199497,40,Self-employed-not incorporated,35,17,Bachelors degree(BA AB BS),0,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Sales,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,50,95,-50000
199498,50,Private,42,26,High school graduate,0,Not in universe,Married-civilian spouse present,Medical except hospital,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
199499,59,Private,24,2,Bachelors degree(BA AB BS),0,Not in universe,Married-civilian spouse present,Manufacturing-nondurable goods,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,50000+.
199500,74,State government,44,42,7th and 8th grade,0,Not in universe,Widowed,Social services,Handlers equip cleaners etc,...,NaN,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
199501,13,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
199502,50,Federal government,29,2,Some college but no degree,0,Not in universe,Married-civilian spouse present,Transportation,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,48,95,-50000
199503,24,Private,33,29,11th grade,0,Not in universe,Never married,Retail trade,Other service,...,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,52,95,-50000
199504,43,Private,22,36,High school graduate,0,Not in universe,Married-civilian spouse present,Manufacturing-nondurable goods,Machine operators assmblrs & inspctrs,...,Mexico,Mexico,Mexico,Foreign born- Not a citizen of U S,0,Not in universe,2,52,95,-50000
199505,33,Private,34,3,High school graduate,0,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,-50000
199506,14,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
199507,25,Self-employed-incorporated,33,16,Some college but no degree,0,Not in universe,Never married,Retail trade,Sales,...,NaN,NaN,NaN,Foreign born- U S citizen by naturalization,0,Not in universe,2,52,94,-50000
199508,62,Private,4,2,Some college but no degree,0,Not in universe,Married-spouse absent,Construction,Executive admin and managerial,...,Greece,United-States,United-States,Native- Born in the United States,2,Yes,1,52,95,50000+.
199509,47,Local government,43,12,Doctorate degree(PhD EdD),0,Not in universe,Married-civilian spouse present,Education,Professional specialty,...,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,52,94,50000+.
199510,25,Private,33,41,Some college but no degree,0,Not in universe,Never married,Retail trade,Handlers equip cleaners etc,...,United-States,Germany,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
199511,47,Private,23,37,Some college but no degree,0,Not in universe,Married-civilian spouse present,Manufacturing-nondurable goods,Machine operators assmblrs & inspctrs,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,-50000
199512,71,Not in universe,0,0,High school graduate,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,-50000
199513,57,Private,9,37,9th grade,0,Not in universe,Divorced,Manufacturing-durable goods,Machine operators assmblrs & inspctrs,...,Dominican-Republic,Dominican-Republic,Dominican-Republic,Foreign born- Not a citizen of U S,0,Not in universe,2,52,95,-50000
199514,51,Private,33,19,10th grade,0,Not in universe,Widowed,Retail trade,Sales,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
199515,87,Not in universe,0,0,High school graduate,0,Not in universe,Widowed,Not in universe or children,Not in universe,...,NaN,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,-50000
199516,3,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
199517,39,Private,43,26,Bachelors degree(BA AB BS),0,Not in universe,Never married,Education,Adm support including clerical,...,Mexico,Mexico,Mexico,Foreign born- Not a citizen of U S,2,Not in universe,2,52,95,-50000
199518,87,Not in universe,0,0,7th and 8th grade,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,Canada,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,-50000
199519,65,Self-employed-incorporated,37,2,11th grade,0,Not in universe,Married-civilian spouse present,Business and repair services,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
199520,47,Not in universe,0,0,Some college but no degree,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,Poland,Poland,Germany,Foreign born- U S citizen by naturalization,0,Not in universe,2,52,95,-50000
199521,16,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,-50000
199522,32,Private,42,30,High school graduate,0,Not in universe,Never married,Medical except hospital,Other service,...,NaN,NaN,NaN,Foreign born- Not a citizen of U S,0,Not in universe,2,52,94,-50000

In [39]:
ad_df.isnull().sum()

AAGE              0
ACLSWKR           0
ADTIND            0
ADTOCC            0
AHGA              0
AHRSPAY           0
AHSCOL            0
AMARITL           0
AMJIND            0
AMJOCC            0
ARACE             0
AREORGN           0
ASEX              0
AUNMEM            0
AUNTYPE           0
AWKSTAT           0
CAPGAIN           0
CAPLOSS           0
DIVVAL            0
FILESTAT          0
GRINREG           0
GRINST          708
HHDFMX            0
HHDREL            0
MARSUPWT          0
MIGMTR1       99696
MIGMTR3       99696
MIGMTR4       99696
MIGSAME           0
MIGSUN        99696
NOEMP             0
PARENT            0
PEFNTVTY       6713
PEMNTVTY       6119
PENATVTY       3393
PRCITSHP          0
SEOTR             0
VETQVA            0
VETYN             0
WKSWORK           0
YEAR              0
INCOME_IND        0
dtype: int64

In [16]:
ad_df

,AAGE,ACLSWKR,ADTIND,ADTOCC,AHGA,AHRSPAY,AHSCOL,AMARITL,AMJIND,AMJOCC,...,PEFNTVTY,PEMNTVTY,PENATVTY,PRCITSHP,SEOTR,VETQVA,VETYN,WKSWORK,YEAR,INCOME_IND
0,73,Not in universe,0,0,High school graduate,0,Not in universe,Widowed,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,-50000
1,58,Self-employed-not incorporated,4,34,Some college but no degree,0,Not in universe,Divorced,Construction,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
2,18,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,...,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,-50000
3,9,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
4,10,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
5,48,Private,40,10,Some college but no degree,1200,Not in universe,Married-civilian spouse present,Entertainment,Professional specialty,...,Philippines,United-States,United-States,Native- Born in the United States,2,Not in universe,2,52,95,-50000
6,42,Private,34,3,Bachelors degree(BA AB BS),0,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
7,28,Private,4,40,High school graduate,0,Not in universe,Never married,Construction,Handlers equip cleaners etc,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,30,95,-50000
8,47,Local government,43,26,Some college but no degree,876,Not in universe,Married-civilian spouse present,Education,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,-50000
9,34,Private,4,37,Some college but no degree,0,Not in universe,Married-civilian spouse present,Construction,Machine operators assmblrs & inspctrs,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
10,8,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
11,32,Not in universe,0,0,High school graduate,0,Not in universe,Never married,Not in universe or children,Not in universe,...,?,?,?,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,-50000
12,51,Private,4,34,Some college but no degree,0,Not in universe,Married-civilian spouse present,Construction,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
13,46,Private,37,31,High school graduate,0,Not in universe,Divorced,Business and repair services,Other service,...,Columbia,Columbia,Columbia,Foreign born- Not a citizen of U S,0,Not in universe,2,52,94,-50000
14,26,Private,24,12,Bachelors degree(BA AB BS),0,Not in universe,Never married,Manufacturing-nondurable goods,Professional specialty,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,-50000
15,13,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
16,47,Private,39,36,Bachelors degree(BA AB BS),0,Not in universe,Never married,Personal services except private HH,Machine operators assmblrs & inspctrs,...,Germany,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,-50000
17,39,Not in universe,0,0,10th grade,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,Mexico,Mexico,Mexico,Foreign born- Not a citizen of U S,0,Not in universe,2,0,94,-50000
18,16,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,...,United-States,El-Salvador,United-States,Native- Born in the United States,0,Not in universe,2,0,95,-50000
19,35,Private,12,41,High school graduate,0,Not in universe,Married-civilian spouse present,Manufacturing-durable goods,Handlers equip cleaners etc,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,49,95,-50000
20,12,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
21,27,Self-employed-not incorporated,4,34,Some college but no degree,0,Not in universe,Married-civilian spouse present,Construction,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,1,Not in universe,2,52,94,-50000
22,56,Private,35,22,Some college but no degree,500,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,32,95,-50000
23,46,Private,45,12,Masters degree(MA MS MEng MEd MSW MBA),0,Not in universe,Married-civilian spouse present,Other professional services,Professional specialty,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
24,55,Not in universe,0,0,Some college but no degree,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,Japan,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,94,-50000
25,2,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
26,1,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,?,?,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
27,37,Private,3,34,Some college but no degree,0,Not in universe,Married-civilian spouse present,Mining,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,-50000
28,4,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,95,-50000
29,37,Private,4,2,Bachelors degree(BA AB BS),0,Not in universe,Never married,Construction,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199493,13,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
199494,5,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
199495,44,Self-employed-not incorporated,38,2,Some college but no degree,0,Not in universe,Married-civilian spouse present,Business and repair services,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,50,94,-50000
199496,1,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
199497,40,Self-employed-not incorporated,35,17,Bachelors degree(BA AB BS),0,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Sales,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,50,95,-50000
199498,50,Private,42,26,High school graduate,0,Not in universe,Married-civilian spouse present,Medical except hospital,Adm support including clerical,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
199499,59,Private,24,2,Bachelors degree(BA AB BS),0,Not in universe,Married-civilian spouse present,Manufacturing-nondurable goods,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,50000+.
199500,74,State government,44,42,7th and 8th grade,0,Not in universe,Widowed,Social services,Handlers equip cleaners etc,...,?,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
199501,13,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
199502,50,Federal government,29,2,Some college but no degree,0,Not in universe,Married-civilian spouse present,Transportation,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,48,95,-50000
199503,24,Private,33,29,11th grade,0,Not in universe,Never married,Retail trade,Other service,...,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,52,95,-50000
199504,43,Private,22,36,High school graduate,0,Not in universe,Married-civilian spouse present,Manufacturing-nondurable goods,Machine operators assmblrs & inspctrs,...,Mexico,Mexico,Mexico,Foreign born- Not a citizen of U S,0,Not in universe,2,52,95,-50000
199505,33,Private,34,3,High school graduate,0,Not in universe,Married-civilian spouse present,Finance insurance and real estate,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,-50000
199506,14,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
199507,25,Self-employed-incorporated,33,16,Some college but no degree,0,Not in universe,Never married,Retail trade,Sales,...,?,?,?,Foreign born- U S citizen by naturalization,0,Not in universe,2,52,94,-50000
199508,62,Private,4,2,Some college but no degree,0,Not in universe,Married-spouse absent,Construction,Executive admin and managerial,...,Greece,United-States,United-States,Native- Born in the United States,2,Yes,1,52,95,50000+.
199509,47,Local government,43,12,Doctorate degree(PhD EdD),0,Not in universe,Married-civilian spouse present,Education,Professional specialty,...,United-States,United-States,United-States,Native- Born in the United States,2,Not in universe,2,52,94,50000+.
199510,25,Private,33,41,Some college but no degree,0,Not in universe,Never married,Retail trade,Handlers equip cleaners etc,...,United-States,Germany,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
199511,47,Private,23,37,Some college but no degree,0,Not in universe,Married-civilian spouse present,Manufacturing-nondurable goods,Machine operators assmblrs & inspctrs,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,95,-50000
199512,71,Not in universe,0,0,High school graduate,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,-50000
199513,57,Private,9,37,9th grade,0,Not in universe,Divorced,Manufacturing-durable goods,Machine operators assmblrs & inspctrs,...,Dominican-Republic,Dominican-Republic,Dominican-Republic,Foreign born- Not a citizen of U S,0,Not in universe,2,52,95,-50000
199514,51,Private,33,19,10th grade,0,Not in universe,Widowed,Retail trade,Sales,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
199515,87,Not in universe,0,0,High school graduate,0,Not in universe,Widowed,Not in universe or children,Not in universe,...,?,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,-50000
199516,3,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,-50000
199517,39,Private,43,26,Bachelors degree(BA AB BS),0,Not in universe,Never married,Education,Adm support including clerical,...,Mexico,Mexico,Mexico,Foreign born- Not a citizen of U S,2,Not in universe,2,52,95,-50000
199518,87,Not in universe,0,0,7th and 8th grade,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,Canada,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,-50000
199519,65,Self-employed-incorporated,37,2,11th grade,0,Not in universe,Married-civilian spouse present,Business and repair services,Executive admin and managerial,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,-50000
199520,47,Not in universe,0,0,Some college but no degree,0,Not in universe,Married-civilian spouse present,Not in universe or children,Not in universe,...,Poland,Poland,Germany,Foreign born- U S citizen by naturalization,0,Not in universe,2,52,95,-50000
199521,16,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,-50000
199522,32,Private,42,30,High school graduate,0,Not in universe,Never married,Medical except hospital,Other service,...,?,?,?,Foreign born- Not a citizen of U S,0,Not in universe,2,52,94,-50000

In [42]:
predictor_list = list(ad_df.columns.values)
predictor_list.remove('INCOME_IND')

predictor_list

['AAGE',
 'ACLSWKR',
 'ADTIND',
 'ADTOCC',
 'AHGA',
 'AHRSPAY',
 'AHSCOL',
 'AMARITL',
 'AMJIND',
 'AMJOCC',
 'ARACE',
 'AREORGN',
 'ASEX',
 'AUNMEM',
 'AUNTYPE',
 'AWKSTAT',
 'CAPGAIN',
 'CAPLOSS',
 'DIVVAL',
 'FILESTAT',
 'GRINREG',
 'GRINST',
 'HHDFMX',
 'HHDREL',
 'MARSUPWT',
 'MIGMTR1',
 'MIGMTR3',
 'MIGMTR4',
 'MIGSAME',
 'MIGSUN',
 'NOEMP',
 'PARENT',
 'PEFNTVTY',
 'PEMNTVTY',
 'PENATVTY',
 'PRCITSHP',
 'SEOTR',
 'VETQVA',
 'VETYN',
 'WKSWORK',
 'YEAR']

In [ ]:
predictor_list.remove('domestic_gross')
predictor_list.remove('tomatoRating')
predictor_list.remove('new_title')

#fit the lasso model, which get selection and estimation at one step.
#if you want to see which variable is significant, there is an easy way:
#just look at the coefficients, greater than 0 means that it is used for prediction

from sklearn.linear_model import LassoCV
clf = LassoCV(cv=20).fit(train[predictor_list],train.domestic_gross)
Y_pred = clf.predict(test[predictor_list])

print(clf.coef_)

#calculate the mean_squared_error
from sklearn.metrics import mean_squared_error
print mean_squared_error(Y_pred, test.domestic_gross)